<div align="center">

# PAO25_25_08_Python_+Pandas

### 8 de Julio de 2026

<br>

<img src="img/logoitqv1.jpg" width="650">

<br><br>

</div>

# 0.1 01MIAR - Estructuras de datos, +Pandas

<div align="center">

<img src="img/python_logo.png" width="550">

</div>

<div align="left">

### Eric Campoverde

<a href="https://github.com/EricJordy/MachineLearning_teoria">Repositorio Git</a>

</div>

<hr style="height:3px;border:none;background:#b30000;">

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [3]:
np.__version__

'2.3.5'

## 1 Operaciones en pandas
Búsqueda

In [4]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  1  0  5
1  4  3  2

In [5]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [6]:
# buscando valores
display(frame.isin([3,2])) #--> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False  False
1  False   True   True

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0  False  False  False
1   True  False  False

[[False False False]
 [ True False False]]

numpy.ndarray

In [9]:
# Crear una máscara que indique qué valores del DataFrame
# son mayores o iguales que 2.
mask = frame >= 2

# Contar cuántos valores cumplen la condición.
print(mask.values.sum())

# Mostrar la máscara.
display(mask)

4

       A      B     C
0  False  False  True
1   True   True  True

### Ordenación

In [10]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))

indices = list(range(5))
shuffle(indices) # mezcla indices

frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
3  16   8  15  16
0   3  14  14  17
2  13  17   7  15
4   2   7   9   1
1  12  15   2  12

In [11]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   2   7   9   1
3  16   8  15  16
2  13  17   7  15
1  12  15   2  12
0   3  14  14  17

    D   A   C   B
3  16   8  15  16
0   3  14  14  17
2  13  17   7  15
4   2   7   9   1
1  12  15   2  12

In [12]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
3  16  15  16   8
0   3  14  17  14
2  13   7  15  17
4   2   9   1   7
1  12   2  12  15

In [13]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
4   2   7   9   1
3  16   8  15  16
0   3  14  14  17
1  12  15   2  12
2  13  17   7  15

In [14]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    C   D   B   A
3  15  16  16   8
0  14   3  17  14
2   7  13  15  17
4   9   2   1   7
1   2  12  12  15

In [15]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
2  13  17   7  15
1  12  15   2  12
0   3  14  14  17
3  16   8  15  16
4   2   7   9   1

### Ranking
- Construir un ranking de valores

In [16]:
display(frame)

    D   A   C   B
2  13  17   7  15
1  12  15   2  12
0   3  14  14  17
3  16   8  15  16
4   2   7   9   1

In [17]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
2  2.0  4.0  1.0  3.0
1  3.0  4.0  1.0  3.0
0  1.0  3.0  3.0  4.0
3  4.0  1.0  2.0  4.0
4  2.0  3.0  4.0  1.0

In [19]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

15
14
9
7
2

## 2 Operaciones
Operaciones matemáticas entre objetos

In [20]:
# Generar una matriz de 4 filas y 4 columnas
# con números enteros aleatorios entre 0 y 99.
matrixA = np.random.randint(100, size=(4, 4))

# Generar una segunda matriz con las mismas dimensiones.
matrixB = np.random.randint(100, size=(4, 4))

# Convertir la primera matriz en un DataFrame.
frameA = pd.DataFrame(matrixA)

# Convertir la segunda matriz en un DataFrame.
frameB = pd.DataFrame(matrixB)

# Mostrar el primer DataFrame.
display(frameA)

# Mostrar el segundo DataFrame.
display(frameB)

    0   1   2   3
0   3  51  19  52
1  62  32   6  69
2  69  21   6  22
3  33  37  16  59

    0   1   2   3
0  38  88  53  78
1  48  26  68  37
2   3  17  14  41
3  82  61  65  58

In [21]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1   2    3
0   41  139  72  130
1  110   58  74  106
2   72   38  20   63
3  115   98  81  117

In [22]:
display(frameB- frameA == frameB.sub(frameA))
display(frameB- frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0  35  37  34  26
1 -14  -6  62 -32
2 -66  -4   8  19
3  49  24  49  -1

In [23]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0   3  51  19  52
1  62  32   6  69
2  69  21   6  22
3  33  37  16  59

    0   1   2
0  96  39  43
1  14  11   1
2  92  90   0

       0      1     2   3
0   99.0   90.0  62.0 NaN
1   76.0   43.0   7.0 NaN
2  161.0  111.0   6.0 NaN
3    NaN    NaN   NaN NaN

In [24]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1     2     3
0   99.0   90.0  62.0  52.0
1   76.0   43.0   7.0  69.0
2  161.0  111.0   6.0  22.0
3   33.0   37.0  16.0  59.0

Operadores aritméticos solo válidos en elementos aceptables

In [26]:
# Crear un DataFrame con dos filas y dos columnas que contienen texto.
frameD = pd.DataFrame({
    0: ['a', 'b'],
    1: ['d', 'f']
})

# Mostrar el DataFrame.
display(frameD)

# Intentar restar un DataFrame numérico con otro de texto.
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [27]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df- df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  2  3  9  0
1  2  8  2  4
2  1  5  8  6

A    2
B    3
C    9
D    0
Name: 0, dtype: int32

pandas.core.series.Series

   A  B  C  D
0  0  0  0  0
1  0  5 -7  4
2 -1  2 -1  6

   A  B  C  D
0  0  0  0  0
1  0  5 -7  4
2 -1  2 -1  6

   A  B  C  D
0  0  1  7 -2
1  0  6  0  2
2  0  4  7  5

pandas se basa en NumPy, np operadores binarios y unarios son aceptables

<div align="center">

<table>
    <thead>
        <tr>
            <th>Tipo</th>
            <th>Operación</th>
            <th>Descripción</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>Unario</td><td>abs</td><td>Valor absoluto de cada elemento</td></tr>
        <tr><td></td><td>sqrt</td><td>Raíz cuadrada de cada
elemento</td></tr>
        <tr><td></td><td>exp</td><td>e^x, siendo x cad
elemento</td></tr>
        <tr><td></td><td>log, log10, log2</td><td>Logaritmos en distintas bases de cada elemento</td></tr>
        <tr><td></td><td>sign</td><td>Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo)</td></tr>
        <tr><td></td><td>ceil</td><td>Redondea cada elemento
por arriba</td></tr>
        <tr><td></td><td>floor</td><td>Redondea cada elemento por abajo</td></tr>
        <tr><td></td><td>isnan</td><td>Retorna si cada elemento es Nan</td></tr>
        <tr><td></td><td>cos, sin, tan</td><td>Operaciones
trigonométricas en cada elemento</td></tr>
        <tr><td></td><td>arccos, arcsin, arctan</td><td>Inversas de operaciones trigonométricas en cada elemento</td></tr>
        <tr><td>Binario</td><td>add</td><td>Suma de dos arrays</td></tr>
        <tr><td></td><td>substract</td><td>Resta de dos arrays</td></tr>
        <tr><td></td><td>multiply</td><td>Multiplicación de dos arrays</td></tr>
        <tr><td></td><td>divide</td><td>División de dos arrays</td></tr>
        <tr><td></td><td>maximum, minimum</td><td>Retorna el valor máximo/mínimo de cada pareja de elementos</td></tr>
        <tr><td></td><td>equal, not_equal</td><td>Retorna la comparación (igual o no igual) de cada pareja de elementos</td></tr>
        <tr><td></td><td>greater, greater_equal, less, less_equal</td><td>Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos </td></tr>
    </tbody>
</table>

</div>

Aplicación de funciones a medida con lambda

In [28]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)

print(frame.apply(lambda x : x.max()- x.min(), axis = 1)) # diferencia por columna

   A  B  C  D
0  3  5  0  9
1  9  5  9  5
2  4  8  6  0

0    9
1    4
2    8
dtype: int64

In [29]:
def max_min(x):
    return x.max()- x.min()
print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    6
B    3
C    9
D    9
dtype: int64

In [30]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max()- x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  7  4  7  6
1  4  5  3  3
2  1  6  5  7

0    3
1    2
2    6
dtype: int64

## 3 Estadística descriptiva
- Análisis preliminar de los datos
- Para Series y DataFrame

<div align="center">

<table>
    <thead>
        <tr>
            <th>Operador</th>
            <th>Descripción</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>count</td><td>Número de valores no NaN</td></tr>
        <tr><td>describe</td><td>Conjunto de estadísticas sumarias</td></tr>
        <tr><td>min, max</td><td>Valores mínimo y máximo</td></tr>
        <tr><td>argmin, argmax</td><td>Índices posicionales del valor mínimo y máximo</td></tr>
        <tr><td>idxmin, idxmax</td><td>Indices semánticos del valor mínimo y máximo</td></tr>
        <tr><td>sum</td><td>Suma de los elementos</td></tr>
        <tr><td>mean</td><td>Media de los elementos</td></tr>
        <tr><td>median</td><td>Mediana de los elementos</td></tr>
        <tr><td>mad</td><td>Desviación absoluta media del valor medio</td></tr>
        <tr><td>var</td><td>Varianza de los elementos</td></tr>
        <tr><td>std</td><td>Desviación estándar de los elementos</td></tr>
        <tr><td>cumsum</td><td>Suma acumulada de los elementos</td></tr>
        <tr><td>diff</td><td>Diferencia aritmética de los elementos</td></tr>
    </tbody>
</table>

</div>

In [31]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30],
                "puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }

frame = pd.DataFrame(diccionario)
display(frame)

display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [32]:
# operadores básicos
print(frame.sum())

display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [33]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [34]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [35]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [36]:
print(frame['edad'].std())

10.996211468804457

In [37]:
frame['edad'].idxmax()

0

In [38]:
frame['puntos'].idxmin()

1

In [39]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [40]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [41]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

### 3.1 Agregaciones

In [42]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [43]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [44]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [45]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [46]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [47]:
# Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30

display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

### 3.2 Correlaciones
pandas incluye métodos para analizar correlaciones- Relación matemática entre dos variables
(-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)- obj.corr(obj2)
´> medida de correlación entre los datos de ambos objetos- https://blogs.oracle.com/ai-and
datascience/post/introduction-to-correlation
### 3.2.1 Ejemplo Fuel efficiency
- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [48]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

mpg_data = pd.read_csv(path, sep='\s+', header=None,
            names = ['mpg', 'cilindros', 'desplazamiento','potencia',
            'peso', 'aceleracion', 'año', 'origen', 'nombre'],
            na_values='?', engine='c')

In [49]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
281,19.8,6,200.0,85.0,2990.0,18.2,79,1,mercury zephyr 6
329,44.6,4,91.0,67.0,1850.0,13.8,80,3,honda civic 1500 gl
325,44.3,4,90.0,48.0,2085.0,21.7,80,2,vw rabbit c (diesel)
100,18.0,6,250.0,88.0,3021.0,16.5,73,1,ford maverick
202,17.5,6,258.0,95.0,3193.0,17.8,76,1,amc pacer d/l

In [50]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [51]:
mpg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    object
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB

### 3.2.2 Correlaciones entre valores

In [52]:
mpg_data['mpg'].corr(mpg_data['peso'])     # + mpg =- peso

np.float64(-0.8317409332443351)

In [53]:
mpg_data['peso'].corr(mpg_data['aceleracion'])      # + peso =- aceleracion

np.float64(-0.4174573199403932)

### 3.2.3 Correlaciones entre todos los valores

In [54]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [55]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [56]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [57]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [58]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: object

In [59]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax()   #consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: object

In [60]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: object

In [61]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

### 3.3 Ejercicios
- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb

### 1. Import pandas under the alias pd.

In [62]:
# Importar la librería pandas con el alias pd 
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [67]:
# Mostrar la versión instalada de pandas 
pd.__version__

'2.3.3'

### 3. Print out all the version information of the libraries that are required by the pandas library.

In [68]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
python                : 3.13.9
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Spanish_Ecuador.1252

pandas                : 2.3.3
numpy                 : 2.3.5
pytz                  : 2025.2
dateutil              : 2.9.0.post0
pip                   : 25.3
Cython                : None
sphinx                : 8.2.3
IPython               : 9.7.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
blosc                 : None
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.10.0
html5lib              : 1.1
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.6
lxml.etree            : 5.3.0
matplotlib            : 3.10.6
numba                 : 0.62.1
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 21.0.0
pyreadstat            : None
pytest                : 8.4.2
python-calamine       : None
pyxlsb                : None
s3fs                  : 2025.10.0
scipy                 : 1.16.3
sqlalchemy            : 2.0.43
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.10.1
xlrd                  : None
xlsxwriter            : None
zstandard             : 0.24.0
tzdata                : 2025.2
qtpy                  : 2.4.3
pyqt5                 : None

### 4. Create a DataFrame df from this dictionary data which has the index labels

In [70]:
# Importar las librerías necesarias
import pandas as pd
import numpy as np

# Crear el diccionario con los datos
data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

# Crear las etiquetas
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [71]:
# Crear el DataFrame y utilizar labels como índice 
df = pd.DataFrame(data, index=labels) 

# Mostrar el DataFrame 
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 5. Display a summary of the basic information about this DataFrame and its data (hint: there is a single method that can be called on the DataFrame).

In [72]:
# Mostrar información de las columnas, tipos de datos y valores no nulos 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

### 6. Return the first 3 rows of the DataFrame df

In [73]:
# Mostrar las primeras tres filas 
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame df

In [74]:
# Seleccionar dos columnas del DataFrame 
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows [3, 4, 8] and in columns ['animal', 'age']

In [75]:
# Seleccionar las filas por posición y las columnas animal y age 
df.iloc[[3, 4, 8]][['animal', 'age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3

In [87]:
# Crear una condición para visitas mayores que 3 
resultado = df[df['visits'] > 2] # le cambié a 2 porq no habia mayores de 3
resultado

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

### 10. Select the rows where the age is missing, i.e. it is NaN

In [84]:
# isna identifica los valores faltantes o NaN 
resultado = df[df['age'].isna()]
resultado

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat and the age is less than 3.

In [83]:
# Seleccionar las filas que cumplan las dos condiciones 
resultado = df[ 
    (df['animal'] == 'cat') & 
    (df['age'] < 3) ]
resultado

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive)

In [88]:
# Seleccionar edades desde 2 hasta 4, incluyendo ambos valores 
resultado = df[df['age'].between(2, 4)] 
resultado

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5

In [90]:
# Cambiar el valor de la columna age en la fila f 
df.loc['f', 'age'] = 1.5 

# Mostrar la fila modificada 
df.loc['f']

animal      cat
age         1.5
visits        3
priority     no
Name: f, dtype: object

### 14. Calculate the sum of all visits in df (i.e. find the total number of visits)

In [91]:
# Sumar todos los valores de la columna visits 
total_visitas = df['visits'].sum() 

print("Total de visitas:", total_visitas)

Total de visitas: 19

### 15. Calculate the mean age for each different animal in df

In [92]:
# Agrupar por animal y calcular el promedio de edad 
promedio_edades = df.groupby('animal')['age'].mean() 

promedio_edades

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to df with your choice of values for each column. Then delete that row to return the original DataFrame

In [94]:
# Agregar una nueva fila con valores elegidos
df.loc['k'] = ['rabbit', 2, 1, 'yes']

# Mostrar el DataFrame con la nueva fila
df

#### Para eliminar la fila:

# Eliminar la fila k del DataFrame
df = df.drop('k')

# Mostrar nuevamente el DataFrame
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in df

In [95]:
# Contar cuántas veces aparece cada animal 
cantidad_animales = df['animal'].value_counts() 

cantidad_animales

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort df first by the values in the 'age' in decending order, then by the value in the 'visits' column in ascending order (so row i should be first, and row d should be last)

In [96]:
# Ordenar primero por edad de mayor a menor
# Luego ordenar visitas de menor a mayor 
df_ordenado = df.sort_values( 
    by=['age', 'visits'], 
    ascending=[False, True] )

df_ordenado

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be True and 'no' should be False

In [97]:
# Reemplazar yes por True y no por False 
df['priority'] = df['priority'].map({ 
    'yes': True, 
    'no': False }) 

df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'

In [98]:
# Reemplazar snake por python en la columna animal 
df['animal'] = df['animal'].replace('snake', 'python') 

df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False